name: Run Unit Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go 1.21.3
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.3
        id: go

      - name: Run Unit Tests
        run: go test -v ./...
